language: r
sudo: false
cache: packages
warnings_are_errors: false

before_install:
  - Rscript -e 'install.packages(c("nlme","car"))'

r_github_packages:
  - cran/tcltk
  - cran/relax
  
after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: always
