language: r
warnings_are_errors: false
sudo: false
cache: packages

notifications:
  email:
    on_success: change
    on_failure: always

after_success:
  - Rscript -e 'library(covr);coveralls()'

r_github_packages:
  - jimhester/covr
  